version: "3.6"
services:
  hugo:
    build:
      context: .
    image: paolomainardi/blog:latest
    environment:
      VIRTUAL_HOST: paolomainardi.loc
      VIRTUAL_PORT: 80
    ports:
      - "8080:80"
    working_dir: /app/src
    command: hugo server --bind 0.0.0.0 --port 80 --theme=hugo-coder --baseURL=paolomainardi.loc --buildFuture --buildDrafts --buildExpired
    volumes:
      - $PWD:$PWD
      - .:/app
      - ./output:/output
